### ISSUE TITLE
格式化方法

### ISSUE THREAD

**Issue by NewFuture** [guodf/VSCode-phpfmt#4]
http://www.php-fig.org/psr/psr-2/#1-1-example

function 前面  private  static 等声明会被去掉 

``` php
final public static function bar()
{
}
```

格式化变成了

``` php
function bar()
{}
```

**Comment by guodf** [comment]
php语法要求不严格导致大部分php程序员写出来得代码都是有语法问题的
final，public，static这3个关键字只有在class中才有意义，所以你上面的代码是有语法错误的
只有在面向对象中才有成员的可访问性概念，类之外的都是面向过程写法，所以final，public，static也就失去了它本来的意义
正确的写法如下：

``` php
class Test
{
    final public static function bar()
    {
    }
}
```

**Comment by NewFuture** [comment]
我说的“方法”就是指 class里的function  :smile:
完整写出来就是你这样的，然而格式化就没了

**Comment by guodf** [comment]
我这里可以格式化,phpfmt现在不开源了,这个扩展我也不想维护了,如果你有兴趣可以维护一下
